kind: pipeline
name: build

platform:
  os: linux
  arch: amd64\\\\\\\\\\\\\\\\\\\\\

steps:
  - name: build
    image: amazoncorretto:11
    volumes:
      - name: deps
        path: /root/.m2
    commands:
      - yum -y install git
      - ./gradlew --no-daemon --info build

  - name: release
    image: node:14
    commands:
      - npx semantic-release
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      event:
        exclude:
        - tag

volumes:
  - name: deps
    temp: {}
