name: CI

on:
  push:
    branches: 
      - dev3
  pull_request:
    branches: 
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: [11, 17]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
    - name: Get branch names
      id: branch-name
      uses: tj-actions/branch-names@v5.1
    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.branch-name.outputs.current_branch }}
    - name: Setup Java JDK
      uses: actions/setup-java@v2.5.0
      with:
        distribution: adopt-hotspot
        java-version: ${{ matrix.java-version }}
    - run: ./gradlew --info build
    - name: Upload Test Results
      uses: actions/upload-artifact@v2.3.1
      if: always()
      with:
        name: artifacts
        path: "**/TEST-*.xml"
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: build
    runs-on: ubuntu-latest
    if: always() # execute even on fails

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml
